// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra_radar_position_transform.proto

package infra_radar_transform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransformRequest struct {
	// Car positioning information in the GPS Exchange Format (gpx) (https://www.topografix.com/gpx/1/1/gpx.xsd)
	HostVehicleData []byte `protobuf:"bytes,1,opt,name=host_vehicle_data,json=hostVehicleData,proto3" json:"host_vehicle_data,omitempty"`
	// Asfinag odo radar interface (version 1.20) unzipped json data
	AsfinagNavtechZip    []byte   `protobuf:"bytes,2,opt,name=asfinag_navtech_zip,json=asfinagNavtechZip,proto3" json:"asfinag_navtech_zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransformRequest) Reset()         { *m = TransformRequest{} }
func (m *TransformRequest) String() string { return proto.CompactTextString(m) }
func (*TransformRequest) ProtoMessage()    {}
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00baa78599dec102, []int{0}
}

func (m *TransformRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformRequest.Unmarshal(m, b)
}
func (m *TransformRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformRequest.Marshal(b, m, deterministic)
}
func (m *TransformRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformRequest.Merge(m, src)
}
func (m *TransformRequest) XXX_Size() int {
	return xxx_messageInfo_TransformRequest.Size(m)
}
func (m *TransformRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransformRequest proto.InternalMessageInfo

func (m *TransformRequest) GetHostVehicleData() []byte {
	if m != nil {
		return m.HostVehicleData
	}
	return nil
}

func (m *TransformRequest) GetAsfinagNavtechZip() []byte {
	if m != nil {
		return m.AsfinagNavtechZip
	}
	return nil
}

type TransformResponse struct {
	SensorData           []*SensorData `protobuf:"bytes,1,rep,name=sensor_data,json=sensorData,proto3" json:"sensor_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransformResponse) Reset()         { *m = TransformResponse{} }
func (m *TransformResponse) String() string { return proto.CompactTextString(m) }
func (*TransformResponse) ProtoMessage()    {}
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00baa78599dec102, []int{1}
}

func (m *TransformResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformResponse.Unmarshal(m, b)
}
func (m *TransformResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformResponse.Marshal(b, m, deterministic)
}
func (m *TransformResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformResponse.Merge(m, src)
}
func (m *TransformResponse) XXX_Size() int {
	return xxx_messageInfo_TransformResponse.Size(m)
}
func (m *TransformResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransformResponse proto.InternalMessageInfo

func (m *TransformResponse) GetSensorData() []*SensorData {
	if m != nil {
		return m.SensorData
	}
	return nil
}

func init() {
	proto.RegisterType((*TransformRequest)(nil), "infra_radar_transform.TransformRequest")
	proto.RegisterType((*TransformResponse)(nil), "infra_radar_transform.TransformResponse")
}

func init() {
	proto.RegisterFile("infra_radar_position_transform.proto", fileDescriptor_00baa78599dec102)
}

var fileDescriptor_00baa78599dec102 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x5d, 0x05, 0xc1, 0xac, 0x60, 0x1b, 0x15, 0xd6, 0x7a, 0x91, 0x22, 0x58, 0x3c, 0x04,
	0xdc, 0x7d, 0x05, 0x11, 0xbc, 0x88, 0x54, 0xf1, 0xe0, 0x25, 0x8e, 0xdd, 0xd4, 0x06, 0x6c, 0x26,
	0x66, 0xe2, 0x1e, 0xbc, 0xf8, 0xea, 0x92, 0xa6, 0x5b, 0x8b, 0x08, 0x7b, 0x0b, 0xf3, 0xfd, 0xfc,
	0x33, 0xf9, 0xd8, 0xb9, 0x36, 0xb5, 0x03, 0xe9, 0x60, 0x09, 0x4e, 0x5a, 0x24, 0xed, 0x35, 0x1a,
	0xe9, 0x1d, 0x18, 0xaa, 0xd1, 0xb5, 0xc2, 0x3a, 0xf4, 0xc8, 0x8f, 0xc7, 0xa9, 0x01, 0x66, 0x09,
	0x92, 0x96, 0x15, 0xb6, 0x2d, 0x9a, 0x18, 0xcc, 0x4e, 0xc2, 0xa4, 0x41, 0xf2, 0x2b, 0xd5, 0xe8,
	0xea, 0x5d, 0x2d, 0xc1, 0x43, 0x8f, 0x8e, 0x02, 0x22, 0x65, 0x08, 0xdd, 0xef, 0x34, 0x37, 0x2c,
	0x79, 0x5c, 0xf7, 0x95, 0xea, 0xe3, 0x53, 0x91, 0xe7, 0x97, 0x2c, 0x0d, 0x15, 0xb2, 0xef, 0x90,
	0x21, 0x3e, 0x9b, 0x9c, 0x4d, 0x8a, 0xfd, 0xf2, 0x20, 0x80, 0xa7, 0x38, 0xbf, 0x06, 0x0f, 0x5c,
	0xb0, 0x43, 0xa0, 0x5a, 0x1b, 0x78, 0x93, 0x06, 0x56, 0x5e, 0x55, 0x8d, 0xfc, 0xd2, 0x76, 0xb6,
	0xdd, 0xa5, 0xd3, 0x1e, 0xdd, 0x45, 0xf2, 0xac, 0x6d, 0x7e, 0xc3, 0xd2, 0xd1, 0x3e, 0xb2, 0x68,
	0x48, 0xf1, 0x2b, 0x36, 0x8d, 0x87, 0xad, 0x57, 0xed, 0x14, 0xd3, 0x79, 0x22, 0x90, 0xf4, 0x42,
	0x3c, 0x74, 0x20, 0xec, 0x2a, 0x19, 0x0d, 0xef, 0xf9, 0x37, 0x3b, 0xbd, 0x0d, 0x4e, 0xca, 0xa0,
	0xe4, 0xbe, 0xf7, 0x36, 0x34, 0xf3, 0x17, 0xb6, 0x37, 0x68, 0xe2, 0x17, 0xe2, 0x5f, 0x7d, 0xe2,
	0xef, 0xc7, 0xb3, 0x62, 0x73, 0x30, 0x5e, 0x9c, 0x6f, 0xbd, 0xee, 0x76, 0xfe, 0x16, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x16, 0xba, 0xec, 0xff, 0xc1, 0x01, 0x00, 0x00,
}
